services:
  lotre-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lotre-arisan-app
    restart: unless-stopped
    ports:
      - "3005:3000"
      - "5555:5555"
    volumes:
      - ./db:/app/db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/db/prod.db
      - NEXTAUTH_SECRET=ganti-dengan-secret-jwt-yang-sangat-aman-123456789
      - NEXTAUTH_URL=http://192.168.0.106:3005
